spring:
  application:
    name: store

  profiles:
    active: dev

server:
  port: 8090

##엘라스틱 설정
elasticsearch:
  enabled: false
  host: "localhost"
  port: 9200

#공통 설정 내용
management:
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health, info, shutdown, prometheus
  endpoint:
    shutdown:
      enabled: false
    prometheus:
      enabled: false

#swagger 설정
springdoc:
  packages-to-scan: store.novabook
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    path: /api-docs

rabbitmq:
  queue:
    couponCreateNormal: nova.coupon.create.normal.queue
    couponCreateHighTraffic: nova.coupon.create.hightraffic.queue
    couponRegisterNormal: nova.coupon.register.normal.queue
    couponRegisterHighTraffic: nova.coupon.register.hightraffic.queue
    deadLetter: nova.coupon.deadletter.queue
  exchange:
    couponOperation: nova.coupon.operation.exchange
    deadLetter: nova.coupon.deadletter.exchange
  routing:
    couponCreateNormal: coupon.create.normal
    couponCreateHighTraffic: coupon.create.hightraffic
    couponRegisterNormal: coupon.register.normal
    couponRegisterHighTraffic: coupon.register.hightraffic
