spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource  # 사용할 데이터 소스 타입 (DBCP2)
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    dbcp2:
      initial-size: 2  # 처음 풀(pool)에 할당할 커넥션 개수
      max-total: 6  # 풀에 허용할 최대 커넥션 개수
      max-idle: 6  # 풀에 유지할 수 있는 최대 유휴 커넥션 개수
      min-idle: 2  # 풀에 유지할 최소 유휴 커넥션 개수
      validation-query: SELECT 1  # 커넥션 유효성 검사를 위한 쿼리
      default-auto-commit: true  # 기본 자동 커밋 설정

  rabbitmq:
    listener:
      simple:
        acknowledge-mode: none

  #절대 변경 금지
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql : trace

#유레카 활성화
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

DB_HOST: "localhost"
DB_PORT: 3306
DB_NAME: "be6_supernova_dev"
DB_USERNAME: "root"
DB_PASSWORD: "9eexju!@12"

redis-host: "localhost"
redis-port: 6379
redis-password: "default"

rabbitmq-host: "localhost"
rabbitmq-username: "guest"
rabbitmq-password: "guest"
rabbitmq-port: 5672

IMAGE_SAVE_PATH: "/Users/isehui/nhn-academy/supernova-v2/novabook-back-store/src/main/resources/tmp/"