spring:
  application:
    name: 'store'

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource  # 사용할 데이터 소스 타입 (DBCP2)

    dbcp2:
      initial-size: 2  # 처음 풀(pool)에 할당할 커넥션 개수
      max-total: 6  # 풀에 허용할 최대 커넥션 개수
      max-idle: 6  # 풀에 유지할 수 있는 최대 유휴 커넥션 개수
      min-idle: 2  # 풀에 유지할 최소 유휴 커넥션 개수
      validation-query: SELECT 1  # 커넥션 유효성 검사를 위한 쿼리
      default-auto-commit: true  # 기본 자동 커밋 설정

  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 3000  # 최초 메시지 처리 실패 후 재시도까지의 인터벌 (3초)
          max-interval: 10000    # 최대 재시도 인터벌 (10초)
          max-attempts: 3        # 최대 재시도 횟수
          multiplier: 2.0 # 이전 interval * multiplier = 다음 interval


  #절대 변경 금지
  jpa:
    hibernate:
      ddl-auto: create


logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace

jwt:
  secret: vzxvgsjdgdfjgfdskgjdsfkgjdsfkgkdsfgjdfkgjdfsgdklgjadgslkjgsaklj


#유레카 활성화
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka



